version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: payments_yookassa_backend
    environment:
      - DATABASE_URL=postgresql://payments:payments@postgres:5432/payments_db
      - YOOKASSA_SHOP_ID=your_shop_id
      - YOOKASSA_API_KEY=your_api_key
      - YOOKASSA_SUCCESS_URL=http://localhost:5173/success
      - YOOKASSA_CANCEL_URL=http://localhost:5173/cancel
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build: .
    container_name: payments_yookassa_worker
    command: celery -A app.celery_app.celery worker --loglevel=info -Q payments
    environment:
      - DATABASE_URL=postgresql://payments:payments@postgres:5432/payments_db
      - YOOKASSA_SHOP_ID=your_shop_id
      - YOOKASSA_API_KEY=your_api_key
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  
